replicaCount: 2

images:
  wordpress: 905418351204.dkr.ecr.us-east-1.amazonaws.com/wordpress-custom:latest
  mysql: 905418351204.dkr.ecr.us-east-1.amazonaws.com/mysql-custom:latest
  nginx: 905418351204.dkr.ecr.us-east-1.amazonaws.com/nginx-openresty:latest

storage:
  className: efs-sc
  size: 5Gi

mysql:
  database: wordpress
  user: wpuser
  password: Navinfo123!
  rootPassword: Rootinfo123!

nginx:
  service:
    type: LoadBalancer
    port: 80
